
import type { Product, Category, Testimonial } from './types'

export const categories: Category[] = [
  { id: 'honey', name: 'Organic Honey', description: 'Pure, raw honey from diverse regions of India' },
  { id: 'ghee', name: 'Desi Cow A2 Ghee', description: 'Traditionally churned ghee from grass-fed desi cows' },
  { id: 'snacks', name: 'Healthy Snacks', description: 'Nutritious and delicious snacks made with natural ingredients' },
]

export const products: Product[] = [
  {
    id: 'kashmiri-honey',
    name: 'Kashmiri Saffron Honey',
    category: 'honey',
    price: 750,
    description: 'A divine blend of pure multi-floral honey from the valleys of Kashmir and premium saffron strands This honey is a treat for the senses and a boost for your health',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Kashmir',
    ingredients: ['Raw Multi-floral Honey', 'Saffron Strands'],
    farmerStory: {
      name: 'Ghulam Ahmed',
      story: 'For generations, our family has practiced the art of beekeeping in the pristine meadows of Pahalgam We believe in letting the bees thrive naturally, resulting in honey that is pure and full of life',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Boosts immunity', 'Rich in antioxidants', 'Improves skin health'],
    certifications: ['FSSAI Certified', 'Organic India'],
  },
  {
    id: 'shilajit-honey-twigs',
    name: 'Honey Twigs with Shilajit',
    category: 'honey',
    price: 450,
    description: 'The ultimate natural performance enhancer for gym lovers Infused with pure Himalayan Shilajit, these honey twigs provide a sustained energy release to power you through your workouts',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'honey sticks gym',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Himalayan Region',
    ingredients: ['Raw Honey', 'Shilajit Extract'],
    farmerStory: {
      name: 'Himalayan Herbalists Co-op',
      story: 'We source our Shilajit resin from the highest altitudes of the Himalayas, where it has been forming for centuries We combine this potent mineral with wild honey to create a powerful wellness product',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Boosts stamina and performance', 'Aids in muscle recovery', 'Natural pre-workout energy'],
    certifications: ['FSSAI Certified'],
  },
  {
    id: 'sundarbans-honey',
    name: 'Wild Sundarbans Honey',
    category: 'honey',
    price: 680,
    description: 'A rare and exotic honey collected by traditional honey hunters from the mangrove forests of the Sundarbans It has a unique, slightly saline taste and a rich, dark color',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Sundarbans, West Bengal',
    ingredients: ['Raw Mangrove Honey'],
    farmerStory: {
      name: 'The Moulis community',
      story: 'We are the traditional honey collectors of the Sundarbans Risking our lives, we venture deep into the forests to collect this precious nectar, following ancient sustainable practices',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Natural energy booster', 'Soothes sore throats', 'Aids in digestion'],
  },
  {
    id: 'nepal-magical-honey',
    name: 'Nepal\'s Magical Cliff Honey',
    category: 'honey',
    price: 850,
    description: 'Sourced from the perilous cliffs of the Nepalese Himalayas, this isn\'t just honey—it\'s an adventure in a jar Harvested by brave honey hunters, its unique, slightly intoxicating flavor comes from the nectar of wild rhododendrons A taste of the magic is a taste of the wild',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Himalayas, Nepal',
    ingredients: ['Raw Himalayan Cliff Honey', 'Nectar of Wild Rhododendrons', 'A touch of mountain spirit (just kidding!)'],
    farmerStory: {
      name: 'The Gurung Tribe Hunters',
      story: 'We are the descendants of ancient honey hunters, a tradition passed down through generations We scale treacherous cliffs with nothing but handmade ropes to bring you this liquid gold It is a dangerous dance with nature, but it allows us to share this gift from the mountains with the world',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Provides a unique sensory experience', 'Rich in natural pollen', 'Supports ancient traditions'],
  },
  {
    id: 'gir-ghee',
    name: 'Gir Cow Desi Ghee (1kg)',
    category: 'ghee',
    price: 3000,
    description: 'Pure, hand-churned A2 ghee from the milk of grass-fed Gir cows. Made in small batches using the traditional Bilona method to retain maximum nutrients and flavor. A true superfood.',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Gujarat',
    ingredients: ['A2 Milk from Gir cows'],
    farmerStory: {
      name: 'Ranchodbhai Patel',
      story: 'Our Gir cows are the pride of our farm. They graze freely on organic pastures, and we treat them with love and respect. This ghee is a product of that care, churned by hand to preserve its natural goodness.',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in Omega-3 & 9', 'Boosts metabolism', 'Strengthens immunity', 'Improves digestion'],
    certifications: ['FSSAI Certified', 'Small-Batch Handcrafted'],
  },
   {
    id: 'sahiwal-ghee',
    name: 'Sahiwal Cow Desi Ghee (500g)',
    category: 'ghee',
    price: 1600,
    description: 'Golden, aromatic A2 ghee from the hardy Sahiwal cows of Punjab. This grass-fed ghee is known for its medicinal properties and is made in limited quantities to ensure purity.',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Punjab',
    ingredients: ['A2 Milk from Sahiwal cows'],
    farmerStory: {
      name: 'Balwinder Singh',
      story: 'The Sahiwal is a special cow, and its milk produces ghee of exceptional quality. We follow age-old practices, ensuring that every jar of ghee we produce is a testament to Punjab\'s rich dairy heritage.',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Good for heart health', 'Nourishes skin', 'Anti-inflammatory properties'],
    certifications: ['FSSAI Certified', 'Limited Batch'],
  },
   {
    id: 'kankrej-ghee',
    name: 'Kankrej Cow Desi Ghee (250g)',
    category: 'ghee',
    price: 850,
    description: 'A rare and delightful ghee from the milk of Kankrej cows, native to the Rann of Kutch. This ghee has a unique texture and a rich, nutty flavor. A perfect trial size.',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Kutch, Gujarat',
    ingredients: ['A2 Milk from Kankrej cows'],
    farmerStory: {
      name: 'Kutch Pastoralist Union',
      story: 'Our Kankrej cattle are adapted to the harsh desert climate. The ghee from their milk is a cherished product of our community, made with techniques passed down through generations of Maldharis (pastoralists).',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['High in fat-soluble vitamins', 'Aids in joint lubrication', 'Improves brain function'],
    certifications: ['FSSAI Certified', 'Community Sourced'],
  },
  {
    id: 'ghee-sampler-pack',
    name: 'Desi Ghee Sampler Pack',
    category: 'ghee',
    price: 1200,
    description: 'Can\'t decide which ghee to try? Our sampler pack is the perfect solution! Get three 100g jars of our finest A2 cow ghees: Gir, Sahiwal, and Kankrej. Experience the diverse flavors of India.',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Multi-regional',
    ingredients: ['Gir Cow Ghee (100g)', 'Sahiwal Cow Ghee (100g)', 'Kankrej Cow Ghee (100g)'],
    farmerStory: {
      name: 'Various Farmers',
      story: 'This pack represents a journey across India, from the pastures of Gujarat to the fields of Punjab. It\'s a tribute to the dedicated farmers who uphold the traditions of raising native Indian cattle breeds.',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Discover your favorite ghee', 'Perfect for gifting', 'Experience regional diversity'],
    certifications: ['FSSAI Certified', 'Small-Batch Handcrafted'],
  },
  {
    id: 'murrah-buffalo-ghee',
    name: 'Murrah Buffalo Desi Ghee (500g)',
    category: 'ghee',
    price: 950,
    description: 'Rich and creamy ghee made from the milk of Murrah buffaloes, the pride of Haryana. This ghee is known for its high fat content, white color, and granular texture. A delicious alternative to cow ghee.',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Haryana',
    ingredients: ['Buffalo Milk'],
    farmerStory: {
        name: 'Sukhbir Singh',
        story: 'Our Murrah buffaloes are champions, known for their high-quality milk. We make our ghee with traditional methods to ensure it is as pure and delicious as possible. It is the secret ingredient in our family recipes.',
        video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in Calcium and Magnesium', 'Good source of phosphorus', 'Boosts bone health'],
    certifications: ['FSSAI Certified'],
  },
  {
    id: 'millet-cookies',
    name: 'Ragi & Jaggery Cookies',
    category: 'snacks',
    price: 350,
    description: 'A guilt-free snack for all ages These cookies are made from nutrient-dense Ragi (finger millet) and sweetened with natural jaggery No refined sugar, no maida',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Karnataka',
    ingredients: ['Ragi Flour', 'Jaggery', 'A2 Ghee', 'Cardamom'],
    farmerStory: {
      name: 'Sahana Women\'s Collective',
      story: 'We are a group of women from rural Karnataka dedicated to reviving traditional grains Our recipes are passed down through generations, made with love and the finest local ingredients',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in calcium and iron', 'High in fiber', 'Gluten-free'],
  },
  {
    id: 'ladoos',
    name: 'Dry Fruit Ladoos',
    category: 'snacks',
    price: 550,
    description: 'Energy balls made from dates, figs, almonds, and other nuts A perfect, a healthy way to satisfy your sweet cravings without any added sugar',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: ['Dates', 'Figs', 'Almonds', 'Walnuts', 'Pistachios', 'A2 Ghee'],
    farmerStory: {
      name: 'Urban Homemakers',
      story: 'Inspired by our family traditions, we started creating these healthy treats in our home kitchens We source the best quality dry fruits to ensure every ladoo is packed with goodness',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Instant energy boost', 'Rich in vitamins and minerals', 'Good for hair and skin'],
  },
]

export const featuredProducts = [products[0], products[1], products[3], products[4]];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Anjali Sharma',
    location: 'Mumbai, Maharashtra',
    avatar: 'https://placehold.co/100x100.png',
    text: 'The Rajasthani Bilona Ghee is just like what my grandmother used to make The aroma and taste are so pure It has become a staple in my kitchen!',
    rating: 5,
  },
  {
    id: '2',
    name: 'Vikram Patel',
    location: 'Bengaluru, Karnataka',
    avatar: 'https://placehold.co/100x100.png',
    text: 'I was looking for healthy snacks for my kids, and the Ragi cookies are perfect They love the taste, and I\'m happy they are eating something nutritious',
    rating: 5,
  },
  {
    id: '3',
    name: 'Priya Das',
    location: 'Kolkata, West Bengal',
    avatar: 'https://placehold.co/100x100.png',
    text: 'The Sundarbans honey has a very unique flavour I use it in my morning tea every day It feels so natural and rejuvenating Highly recommend!',
    rating: 4,
  },
  {
    id: '4',
    name: 'Rohan Mehta',
    location: 'Delhi',
    avatar: 'https://placehold.co/100x100.png',
    text: 'Finally, a brand that is transparent about its sourcing Reading the farmer stories makes me feel more connected to the food I eat Great initiative!',
    rating: 5,
  },
]
