import type { Product, Category, Testimonial } from './types'

export const categories: Category[] = [
  { id: 'honey', name: 'Organic Honey', description: 'Pure, raw honey from diverse regions of India' },
  { id: 'ghee', name: 'Desi Cow A2 Ghee', description: 'Traditionally churned ghee from grass-fed desi cows' },
  { id: 'snacks', name: 'Healthy Snacks', description: 'Nutritious and delicious snacks made with natural ingredients' },
  { id: 'jaggery', name: 'Artisanal Jaggery', description: 'Traditional and unrefined jaggery from across India' },
]

export const products: Product[] = [
  {
    id: 'kashmiri-honey',
    name: 'Kashmiri Saffron Honey',
    category: 'honey',
    variants: [{ id: 'kh-500g', size: '500g', price: 750 }],
    description: 'A divine blend of pure multi-floral honey from the valleys of Kashmir and premium saffron strands This honey is a treat for the senses and a boost for your health',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Kashmir',
    ingredients: [{ name: 'Raw Multi-floral Honey', source: 'Pahalgam Meadows', batchId: 'KSH-2401', procurementDate: '2024-05-10', expiryDate: '2026-05-09' }, { name: 'Saffron Strands', source: 'Pampore Fields', batchId: 'SFF-2311', procurementDate: '2023-11-20', expiryDate: '2025-11-19' }],
    chunkerStory: {
      name: 'Ghulam Ahmed',
      story: 'For generations, our family has practiced the art of beekeeping in the pristine meadows of Pahalgam We believe in letting the bees thrive naturally, resulting in honey that is pure and full of life',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Boosts immunity', 'Rich in antioxidants', 'Improves skin health'],
    useCase: 'Immunity boosting and improving skin radiance',
    certifications: ['FSSAI Certified', 'Organic India'],
  },
  {
    id: 'shilajit-honey-twigs',
    name: 'Honey Twigs with Shilajit',
    category: 'honey',
    variants: [{ id: 'sht-30pc', size: '30 Twigs', price: 450 }],
    description: 'Our best-selling natural performance enhancer for young people and gym lovers Infused with pure Himalayan Shilajit, these honey twigs provide a sustained energy release to power you through your workouts',
    image: 'https://placehold.co/600x600.png',
    dataAiHint: 'honey sticks gym',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Himalayan Region',
    ingredients: [{ name: 'Raw Honey', source: 'Himalayan Foothills', batchId: 'HNY-2403', procurementDate: '2024-03-15', expiryDate: '2026-03-14' }, { name: 'Shilajit Extract', source: 'Himalayan Higher Altitudes', batchId: 'SHJ-2310', procurementDate: '2023-10-02', expiryDate: '2028-10-01' }],
    chunkerStory: {
      name: 'Himalayan Herbalists Co-op',
      story: 'We source our Shilajit resin from the highest altitudes of the Himalayas, where it has been forming for centuries We combine this potent mineral with wild honey to create a powerful wellness product',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Boosts stamina and performance', 'Aids in muscle recovery', 'Natural pre-workout energy'],
    useCase: 'Enhancing physical performance, stamina, and workout recovery',
    certifications: ['FSSAI Certified'],
  },
  {
    id: 'sundarbans-honey',
    name: 'Wild Sundarbans Honey',
    category: 'honey',
    variants: [{ id: 'sh-500g', size: '500g', price: 680 }],
    description: 'A rare and exotic honey collected by traditional honey hunters from the mangrove forests of the Sundarbans It has a unique, slightly saline taste and a rich, dark color',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Sundarbans, West Bengal',
    ingredients: [{ name: 'Raw Mangrove Honey', source: 'Sundarbans Mangrove Forest', batchId: 'SMH-2404', procurementDate: '2024-04-22', expiryDate: '2026-04-21' }],
    chunkerStory: {
      name: 'The Moulis community',
      story: 'We are the traditional honey collectors of the Sundarbans Risking our lives, we venture deep into the forests to collect this precious nectar, following ancient sustainable practices',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Natural energy booster', 'Soothes sore throats', 'Aids in digestion'],
    useCase: 'General wellness, energy, and soothing respiratory issues',
  },
  {
    id: 'nepal-magical-honey',
    name: 'Nepal\'s Magical Cliff Honey',
    category: 'honey',
    variants: [{ id: 'nmh-250g', size: '250g', price: 850 }],
    description: 'Sourced from the perilous cliffs of the Nepalese Himalayas, this isn\'t just honey—it\'s an adventure in a jar Harvested by brave honey hunters, its unique, slightly intoxicating flavor comes from the nectar of wild rhododendrons A taste of the magic is a taste of the wild',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Himalayas, Nepal',
    ingredients: [{ name: 'Raw Himalayan Cliff Honey', source: 'Nepalese Cliffs', batchId: 'NCH-2402', procurementDate: '2024-02-18', expiryDate: '2026-02-17' }, { name: 'Nectar of Wild Rhododendrons', source: 'Nepalese Cliffs', batchId: 'NCH-2402', procurementDate: '2024-02-18', expiryDate: '2026-02-17' }],
    chunkerStory: {
      name: 'The Gurung Tribe Hunters',
      story: 'We are the descendants of ancient honey hunters, a tradition passed down through generations We scale treacherous cliffs with nothing but handmade ropes to bring you this liquid gold It is a dangerous dance with nature, but it allows us to share this gift from the mountains with the world',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Provides a unique sensory experience', 'Rich in natural pollen', 'Supports ancient traditions'],
    useCase: 'Unique taste experiences and supporting traditional communities',
  },
  {
    id: 'gir-ghee',
    name: 'Gir Cow Desi Ghee',
    category: 'ghee',
    variants: [
        { id: 'gir-250g', size: '250g', price: 800 },
        { id: 'gir-500g', size: '500g', price: 1500 },
        { id: 'gir-1kg', size: '1kg', price: 3000 },
    ],
    description: 'Pure, hand-churned A2 ghee from the milk of grass-fed Gir cows Made in small batches using the traditional Bilona method to retain maximum nutrients and flavor A true superfood',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Gujarat',
    ingredients: [{ name: 'A2 Milk from Gir cows', source: 'Ranchodbhai Patel Farm', batchId: 'GIR-2405', procurementDate: '2024-05-20', expiryDate: '2025-05-19' }],
    chunkerStory: {
      name: 'Ranchodbhai Patel',
      story: 'Our Gir cows are the pride of our farm They graze freely on organic pastures, and we treat them with love and respect This ghee is a product of that care, churned by hand to preserve its natural goodness',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in Omega-3 & 9', 'Boosts metabolism', 'Strengthens immunity', 'Improves digestion'],
    useCase: 'Improving digestion, boosting metabolism and overall immunity',
    certifications: ['FSSAI Certified', 'Small-Batch Handcrafted'],
  },
   {
    id: 'sahiwal-ghee',
    name: 'Sahiwal Cow Desi Ghee',
    category: 'ghee',
    variants: [
        { id: 'sahiwal-250g', size: '250g', price: 450 },
        { id: 'sahiwal-500g', size: '500g', price: 850 },
        { id: 'sahiwal-1kg', size: '1kg', price: 1600 },
    ],
    description: 'Golden, aromatic A2 ghee from the hardy Sahiwal cows of Punjab This grass-fed ghee is known for its medicinal properties and is made in limited quantities to ensure purity',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Punjab',
    ingredients: [{ name: 'A2 Milk from Sahiwal cows', source: 'Balwinder Singh Farm', batchId: 'SAH-2405', procurementDate: '2024-05-18', expiryDate: '2025-05-17' }],
    chunkerStory: {
      name: 'Balwinder Singh',
      story: 'The Sahiwal is a special cow, and its milk produces ghee of exceptional quality We follow age-old practices, ensuring that every jar of ghee we produce is a testament to Punjab\'s rich dairy heritage',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Good for heart health', 'Nourishes skin', 'Anti-inflammatory properties'],
    useCase: 'Supporting heart health and nourishing the skin',
    certifications: ['FSSAI Certified', 'Limited Batch'],
  },
   {
    id: 'kankrej-ghee',
    name: 'Kankrej Cow Desi Ghee',
    category: 'ghee',
    variants: [
        { id: 'kankrej-250g', size: '250g', price: 850 },
        { id: 'kankrej-500g', size: '500g', price: 1600 },
    ],
    description: 'A rare and delightful ghee from the milk of Kankrej cows This ghee has a unique texture and a rich, nutty flavor A perfect trial size',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Uttar Pradesh',
    ingredients: [{ name: 'A2 Milk from Kankrej cows', source: 'Avadh Dairy Collective', batchId: 'KAN-2404', procurementDate: '2024-04-30', expiryDate: '2025-04-29' }],
    chunkerStory: {
      name: 'Avadh Dairy Collective',
      story: 'Our Kankrej cattle are known for their resilience The ghee from their milk is a cherished product of our community, made with techniques passed down through generations',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['High in fat-soluble vitamins', 'Aids in joint lubrication', 'Improves brain function'],
    useCase: 'Supporting brain function and joint health',
    certifications: ['FSSAI Certified', 'Community Sourced'],
  },
  {
    id: 'ghee-sampler-pack',
    name: 'Desi Ghee Sampler Pack',
    category: 'ghee',
    variants: [{ id: 'gsp-300g', size: '3x100g', price: 1200 }],
    description: 'Can\'t decide which ghee to try? Our sampler pack is the perfect solution Get three 100g jars of our finest A2 cow ghees: Gir, Sahiwal, and Kankrej Experience the diverse flavors of India',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Multi-regional',
    ingredients: [{ name: 'Gir Cow Ghee (100g)', source: 'Ranchodbhai Patel Farm', batchId: 'GIR-2405', procurementDate: '2024-05-20', expiryDate: '2025-05-19' }, { name: 'Sahiwal Cow Ghee (100g)', source: 'Balwinder Singh Farm', batchId: 'SAH-2405', procurementDate: '2024-05-18', expiryDate: '2025-05-17' }, { name: 'Kankrej Cow Ghee (100g)', source: 'Avadh Dairy Collective', batchId: 'KAN-2404', procurementDate: '2024-04-30', expiryDate: '2025-04-29' }],
    chunkerStory: {
      name: 'Various Chunkers',
      story: 'This pack represents a journey across India, from the pastures of Gujarat to the fields of Punjab It\'s a tribute to the dedicated chunkers who uphold the traditions of raising native Indian cattle breeds',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Discover your favorite ghee', 'Perfect for gifting', 'Experience regional diversity'],
    useCase: 'Sampling different regional ghees for varied health benefits',
    certifications: ['FSSAI Certified', 'Small-Batch Handcrafted'],
  },
  {
    id: 'murrah-buffalo-ghee',
    name: 'Murrah Buffalo Desi Ghee',
    category: 'ghee',
    variants: [{ id: 'mbg-500g', size: '500g', price: 950 }],
    description: 'Rich and creamy ghee made from the milk of Murrah buffaloes, the pride of Haryana This ghee is known for its high fat content, white color, and granular texture A delicious alternative to cow ghee',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Haryana',
    ingredients: [{ name: 'Buffalo Milk', source: 'Sukhbir Singh Farm', batchId: 'MUR-2405', procurementDate: '2024-05-21', expiryDate: '2025-02-20' }],
    chunkerStory: {
        name: 'Sukhbir Singh',
        story: 'Our Murrah buffaloes are champions, known for their high-quality milk We make our ghee with traditional methods to ensure it is as pure and delicious as possible It is the secret ingredient in our family recipes',
        video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
        photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in Calcium and Magnesium', 'Good source of phosphorus', 'Boosts bone health'],
    useCase: 'Boosting bone health due to high calcium and magnesium content',
    certifications: ['FSSAI Certified'],
  },
  {
    id: 'millet-ragi-cookies',
    name: 'Millet & Ragi Cookies',
    category: 'snacks',
    variants: [
        { id: 'mrc-jg', size: 'Jaggery & Ginger', price: 299 },
        { id: 'mrc-cc', size: 'Chocochip & Flax', price: 329 },
        { id: 'mrc-ca', size: 'Cardamom Almond', price: 329 }
    ],
    description: 'India’s Ancient Grain, Now a Cookie These delicious cookies are rich in fiber, gluten-free, and have a low glycemic index',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Karnataka',
    ingredients: [
      { name: 'Ragi Flour', source: 'GreenHarvest Farms, Mandya', batchId: 'RAG-2406A', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
      { name: 'Jaggery', source: 'Natural Sweeteners Co, Kolhapur', batchId: 'JAG-2405C', procurementDate: '2024-05-15', expiryDate: '2025-05-14' }
    ],
    chunkerStory: {
      name: 'Sahana Women\'s Collective',
      story: 'We are a group of women from rural Karnataka dedicated to reviving traditional grains Our recipes are passed down through generations, made with love and the finest local ingredients',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in fiber', 'Gluten-free', 'Low glycemic index'],
    useCase: 'A healthy, gluten-free snack that is rich in fiber',
  },
  {
    id: 'cone-bites',
    name: 'Dark Chocolate Cone Bites',
    category: 'snacks',
    variants: [{ id: 'dcb-150g', size: '150g', price: 420 }],
    description: 'Bite-sized bliss with no guilt Mini waffle cones filled with delicious date-almond butter and coated in rich dark chocolate',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Mini Waffle Cones', source: 'Local Bakery', batchId: 'WFC-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
        { name: 'Date-Almond Butter', source: 'In-house', batchId: 'DAB-2406', procurementDate: '2024-06-01', expiryDate: '2024-09-01' },
        { name: 'Dark Chocolate', source: 'Indian Cocoa Farms', batchId: 'DC-2405', procurementDate: '2024-05-15', expiryDate: '2025-05-14' }
    ],
    chunkerStory: {
      name: 'Urban Homemakers',
      story: 'We create treats that are both indulgent and healthy These cone bites are our modern take on guilt-free snacking',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Guilt-free indulgence', 'No refined sugar', 'Rich in antioxidants'],
    useCase: 'A healthy dessert or sweet snack without refined sugar',
  },
  {
    id: 'energy-cubes',
    name: 'Honey & Nut Butter Energy Cubes',
    category: 'snacks',
    variants: [{ id: 'ec-200g', size: '200g', price: 380 }],
    description: 'The natural 4PM fix with no crash Made from dates, honey, nut butter, and oats, these cubes are your perfect energy boost',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Dates', source: 'Omani Imports', batchId: 'DAT-2404', procurementDate: '2024-04-10', expiryDate: '2025-04-09' },
        { name: 'Almond Butter', source: 'In-house', batchId: 'ALB-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
        { name: 'Rolled Oats', source: 'Punjab Farms', batchId: 'OAT-2403', procurementDate: '2024-03-20', expiryDate: '2025-09-19' },
        { name: 'Raw Honey', source: 'Himalayan Foothills', batchId: 'HNY-2403', procurementDate: '2024-03-15', expiryDate: '2026-03-14' }
    ],
    chunkerStory: {
      name: 'The Fitness Kitchen',
      story: 'We believe in the power of natural energy Our energy cubes are crafted to provide sustained fuel for active lifestyles, without any artificial ingredients',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Sustained energy release', 'No-crash formula', 'High in protein and fiber'],
    useCase: 'A natural pre-workout or afternoon energy snack',
  },
  {
    id: 'ghee-makhana',
    name: 'Ghee Roasted Makhana',
    category: 'snacks',
    variants: [
        { id: 'gm-ss', size: 'Sea Salt', price: 250 },
        { id: 'gm-m', size: 'Masala', price: 260 }
    ],
    description: 'Your Netflix snack upgrade, Ayurveda-approved High-protein, low-calorie fox nuts roasted in pure A2 ghee',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Bihar',
    ingredients: [
        { name: 'Makhana (Fox Nuts)', source: 'Mithila Region', batchId: 'MKH-2405', procurementDate: '2024-05-10', expiryDate: '2025-05-09' },
        { name: 'A2 Ghee', source: 'Gir Farms', batchId: 'GIR-2405', procurementDate: '2024-05-20', expiryDate: '2025-02-19' }
    ],
    chunkerStory: {
      name: 'Mithila Makhana Chunkers',
      story: 'Makhana has been a part of our culture for centuries We cultivate it in natural ponds and sun-dry it to perfection, preserving its nutritional benefits',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['High in protein', 'Low calorie', 'Rich in minerals'],
    useCase: 'A healthy, crunchy snack for any time of day',
  },
  {
    id: 'saffron-laddoo',
    name: 'Saffron & Almond Laddoo',
    category: 'snacks',
    variants: [{ id: 'sal-200g', size: '200g', price: 480 }],
    description: 'Grandma’s laddoo meets clean eating A luxurious yet clean-ingredient treat, rolled in oat flour and sweetened with dates',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Almonds', source: 'California Orchards', batchId: 'ALM-2403', procurementDate: '2024-03-20', expiryDate: '2025-09-19' },
        { name: 'Saffron', source: 'Kashmir Fields', batchId: 'SFF-2311', procurementDate: '2023-11-20', expiryDate: '2025-11-19' },
        { name: 'Dates', source: 'Omani Imports', batchId: 'DAT-2404', procurementDate: '2024-04-10', expiryDate: '2025-04-09' },
        { name: 'Oat Flour', source: 'In-house', batchId: 'OATF-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' }
    ],
    chunkerStory: {
      name: 'The Heritage Kitchen',
      story: 'We are reinventing traditional Indian sweets for the modern palate Our laddoos carry the warmth of tradition with the benefits of clean, healthy ingredients',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Clean ingredients', 'No refined sugar', 'Luxurious taste'],
    useCase: 'A healthy festive sweet or an indulgent treat',
  },
  {
    id: 'garlic-pita-chips',
    name: 'Garlic Chutney Pita Chips',
    category: 'snacks',
    variants: [{ id: 'gcpc-150g', size: '150g', price: 220 }],
    description: 'The spicy chip your gut loves Baked, not fried, multigrain pita chips coated with a zesty dry garlic and masala chutney',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Multigrain Flour', source: 'Local Millers', batchId: 'MGF-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
        { name: 'Dry Garlic Chutney', source: 'In-house', batchId: 'DGC-2406', procurementDate: '2024-06-01', expiryDate: '2024-09-01' }
    ],
    chunkerStory: {
      name: 'Snacksmiths India',
      story: 'We love bold Indian flavors Our garlic chutney chips are a tribute to the fiery chutneys of Maharashtra, made healthier by baking',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Baked, not fried', 'Made with multigrain', 'Rich in flavor'],
    useCase: 'A healthier alternative to fried chips',
  },
  {
    id: 'chia-jaggery-parfait',
    name: 'Chia & Jaggery Parfait Jars',
    category: 'snacks',
    variants: [{ id: 'cjp-200g', size: '200g Jar', price: 350 }],
    description: 'Breakfast, but prettier And better for your gut Layers of soaked chia seeds, jaggery-sweetened yogurt, and seasonal fruit puree',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Chia Seeds', source: 'Organic Farms', batchId: 'CHS-2405', procurementDate: '2024-05-15', expiryDate: '2025-11-14' },
        { name: 'Yogurt', source: 'Local Dairy', batchId: 'YOG-2406', procurementDate: '2024-06-10', expiryDate: '2024-06-20' },
        { name: 'Jaggery', source: 'Kolhapur Farms', batchId: 'JAG-2405', procurementDate: '2024-05-15', expiryDate: '2025-05-14' },
    ],
    chunkerStory: {
      name: 'The Breakfast Club',
      story: 'We believe that breakfast should be both beautiful and beneficial Our parfait jars are designed to give you a healthy, happy start to your day',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in probiotics', 'High in fiber and Omega-3', 'Naturally sweetened'],
    useCase: 'A healthy and convenient breakfast or light meal',
  },
  {
    id: 'turmeric-cacao-bites',
    name: 'Turmeric Cacao Bites',
    category: 'snacks',
    variants: [{ id: 'tcb-150g', size: '150g', price: 410 }],
    description: 'Golden latte, meet brownie bite Anti-inflammatory bites made with cacao, turmeric, nut butter, and honey',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Cacao Powder', source: 'Kerala Farms', batchId: 'CAC-2404', procurementDate: '2024-04-20', expiryDate: '2025-10-19' },
        { name: 'Turmeric', source: 'Erode Farms', batchId: 'TUR-2403', procurementDate: '2024-03-10', expiryDate: '2025-09-09' },
        { name: 'Almond Butter', source: 'In-house', batchId: 'ALB-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' }
    ],
    chunkerStory: {
      name: 'The Wellness Pantry',
      story: 'Our goal is to create snacks that heal By combining the power of turmeric and cacao, we have made a treat that tastes good and does good',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Anti-inflammatory', 'Rich in antioxidants', 'Mood-boosting'],
    useCase: 'A functional snack to reduce inflammation and boost mood',
  },
  {
    id: 'beetroot-rice-crisps',
    name: 'Beetroot & Saffron Rice Crisps',
    category: 'snacks',
    variants: [{ id: 'bsrc-100g', size: '100g', price: 280 }],
    description: 'Your snack board just got healthier (and pink) Colorful, crunchy, and naturally flavored rice crisps',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Rice Flour', source: 'Southern Plains', batchId: 'RF-2406', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
        { name: 'Beetroot Powder', source: 'Ooty Farms', batchId: 'BTP-2405', procurementDate: '2024-05-20', expiryDate: '2025-05-19' },
        { name: 'Saffron', source: 'Kashmir Fields', batchId: 'SFF-2311', procurementDate: '2023-11-20', expiryDate: '2025-11-19' }
    ],
    chunkerStory: {
      name: 'The Crispy Cracker Co',
      story: 'We believe snacks should be fun and colorful without artificial ingredients Our crisps get their vibrant hues from real vegetables and spices',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['All-natural colors', 'Light and crunchy', 'Low-calorie'],
    useCase: 'A healthy and colorful addition to snack boards and dips',
  },
  {
    id: 'ragi-jaggery-cookies',
    name: 'Ragi & Jaggery Cookies',
    category: 'snacks',
    variants: [{ id: 'mjc-200g', size: '200g', price: 350 }],
    description: 'A guilt-free snack for all ages These cookies are made from nutrient-dense Ragi (finger millet) and sweetened with natural jaggery No refined sugar, no maida',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Karnataka',
    ingredients: [
      { name: 'Ragi Flour', source: 'GreenHarvest Farms, Mandya', batchId: 'RAG-2406A', procurementDate: '2024-06-01', expiryDate: '2024-12-01' },
      { name: 'Jaggery', source: 'Natural Sweeteners Co, Kolhapur', batchId: 'JAG-2405C', procurementDate: '2024-05-15', expiryDate: '2025-05-14' },
      { name: 'A2 Ghee', source: 'Ranchodbhai Patel Farm, Gujarat', batchId: 'GIR-2405', procurementDate: '2024-05-20', expiryDate: '2025-02-19' },
      { name: 'Cardamom', source: 'Spice Altar, Kerala', batchId: 'CRD-2312', procurementDate: '2023-12-10', expiryDate: '2025-06-10' }
    ],
    reports: [
        { name: 'Nutritional Analysis Report', url: '#', date: '2024-06-10' },
        { name: 'Heavy Metal Test Report', url: '#', date: '2024-06-12' },
        { name: 'FSSAI Compliance Certificate', url: '#', date: '2024-01-05' },
    ],
    nutrition: {
        calories: "450 kcal",
        protein: "8g",
        carbohydrates: "60g",
        sugar: "25g",
        fat: "20g",
        fiber: "10g",
        calcium: "344mg",
        iron: "4.5mg"
    },
    chunkerStory: {
      name: 'Sahana Women\'s Collective',
      story: 'We are a group of women from rural Karnataka dedicated to reviving traditional grains Our recipes are passed down through generations, made with love and the finest local ingredients',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in calcium and iron', 'High in fiber', 'Gluten-free'],
    useCase: 'Healthy, gluten-free snacking, good for iron and calcium intake',
  },
  {
    id: 'ladoos',
    name: 'Dry Fruit Ladoos',
    category: 'snacks',
    variants: [{ id: 'dfl-250g', size: '250g', price: 550 }],
    description: 'Energy balls made from dates, figs, almonds, and other nuts A perfect, a healthy way to satisfy your sweet cravings without any added sugar',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'All India',
    ingredients: [
        { name: 'Dates', source: 'Omani Imports', batchId: 'DAT-2404', procurementDate: '2024-04-10', expiryDate: '2025-04-09' },
        { name: 'Figs', source: 'Turkish Imports', batchId: 'FIG-2404', procurementDate: '2024-04-12', expiryDate: '2025-04-11' },
        { name: 'Almonds', source: 'California Orchards', batchId: 'ALM-2403', procurementDate: '2024-03-20', expiryDate: '2025-09-19' },
        { name: 'A2 Ghee', source: 'Balwinder Singh Farm, Punjab', batchId: 'SAH-2405', procurementDate: '2024-05-18', expiryDate: '2025-02-17' },
    ],
    chunkerStory: {
      name: 'Urban Homemakers',
      story: 'Inspired by our family traditions, we started creating these healthy treats in our home kitchens We source the best quality dry fruits to ensure every ladoo is packed with goodness',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Instant energy boost', 'Rich in vitamins and minerals', 'Good for hair and skin'],
    useCase: 'A healthy, sugar-free energy boost',
  },
  {
    id: 'muzaffarnagar-gur',
    name: 'Muzaffarnagar Gur',
    category: 'jaggery',
    variants: [
        { id: 'mg-500g', size: '500g', price: 250 },
        { id: 'mg-1kg', size: '1kg', price: 480 },
    ],
    description: 'Authentic, chemical-free jaggery from the sugarcane belt of Muzaffarnagar Known for its rich, earthy flavor and soft texture, it is a perfect natural sweetener',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Uttar Pradesh',
    ingredients: [{ name: 'Sugarcane Juice', source: 'Chaudhary Sugarcane Farms', batchId: 'SUG-UP-2401', procurementDate: '2024-01-20', expiryDate: '2025-01-19' }],
    chunkerStory: {
      name: 'The Chaudhary Family',
      story: 'For over a century, our family has been cultivating sugarcane and making gur using traditional methods We use no chemicals, only the pure juice of our sun-kissed cane, to bring you a taste of real Uttar Pradesh',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in iron and magnesium', 'Natural detoxifier', 'Boosts energy levels'],
    useCase: 'A natural sweetener rich in iron, good for managing iron deficiencies',
    certifications: ['FSSAI Certified', 'Chemical-Free'],
  },
  {
    id: 'kolhapuri-gul',
    name: 'Kolhapuri Gul',
    category: 'jaggery',
    variants: [
        { id: 'kg-500g', size: '500g', price: 280 },
        { id: 'kg-1kg', size: '1kg', price: 540 },
    ],
    description: 'Famous for its unique dark color and rich, mineral-heavy taste This jaggery from Kolhapur is made in traditional "gurhals" and is a GI-tagged product, ensuring its authenticity',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Maharashtra',
    ingredients: [{ name: 'Sugarcane Juice', source: 'Kolhapur Jaggery Cooperative', batchId: 'SUG-MH-2402', procurementDate: '2024-02-15', expiryDate: '2025-02-14' }],
    chunkerStory: {
      name: 'Kolhapur Jaggery Cooperative',
      story: 'We are a cooperative of over 100 small chunkers dedicated to preserving the legacy of Kolhapuri Gul Our jaggery is a symbol of our collective effort and the rich soil of Maharashtra',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Excellent source of minerals', 'Cleanses the respiratory tract', 'Aids in digestion'],
    useCase: 'A mineral-rich sweetener that can aid in digestion and respiratory health',
    certifications: ['GI Tagged', 'FSSAI Certified'],
  },
  {
    id: 'marayoor-sharkara',
    name: 'Marayoor Jaggery (Sharkara)',
    category: 'jaggery',
    variants: [{ id: 'ms-500g', size: '500g', price: 320 }],
    description: 'A premium, dark brown jaggery from the Marayoor region of Kerala Made from a special variety of sugarcane, it is produced in a traditional way and has a very low salt content, giving it a unique taste',
    image: 'https://placehold.co/600x600.png',
    images: ['https://placehold.co/600x600.png', 'https://placehold.co/600x600.png', 'https://placehold.co/600x600.png'],
    region: 'Kerala',
    ingredients: [{ name: 'Sugarcane Juice', source: 'Marayoor Sugarcane Growers', batchId: 'SUG-KL-2312', procurementDate: '2023-12-25', expiryDate: '2024-12-24' }],
    chunkerStory: {
      name: 'Marayoor Sugarcane Growers',
      story: 'The unique climate of Marayoor gives our sugarcane its special sweetness We make our jaggery in underground pits, a method that has been used for centuries, to create this delicious and healthy Sharkara',
      video: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
      photo: 'https://placehold.co/300x300.png',
    },
    healthBenefits: ['Rich in antioxidants', 'Low sodium content', 'Traditional Ayurvedic ingredient'],
    useCase: 'A low-sodium, antioxidant-rich sweetener used in traditional wellness practices',
    certifications: ['GI Tagged', 'FSSAI Certified'],
  },
]

export const featuredProducts = [products[3], products[4], products[9], products[20]];

export const testimonials: Testimonial[] = [
  {
    id: '4',
    name: 'Allen',
    location: 'IIM Calcutta',
    avatar: 'https://placehold.co/100x100.png',
    text: 'Finally, a brand that is transparent about its sourcing Reading the chunker stories makes me feel more connected to the food I eat Great initiative',
    rating: 5,
  },
  {
    id: '5',
    name: 'Anamika Rathod',
    location: 'IIT Chennai',
    avatar: 'https://placehold.co/100x100.png',
    text: 'The quality of the products is outstanding You can really taste the difference I love the Shilajit Honey Twigs, they are my go-to pre-workout boost',
    rating: 5,
  },
  {
    id: '1',
    name: 'Kuldeep Meena',
    location: 'IIT Bombay',
    avatar: 'https://placehold.co/100x100.png',
    text: 'The Gir Cow Ghee is just like what my grandmother used to make The aroma and taste are so pure It has become a staple in my kitchen',
    rating: 5,
  },
  {
    id: '2',
    name: 'Ashok NS',
    location: 'IIT Bombay',
    avatar: 'https://placehold.co/100x100.png',
    text: 'I was looking for healthy snacks for my kids, and the Ragi cookies are perfect They love the taste, and I\'m happy they are eating something nutritious',
    rating: 5,
  },
  {
    id: '3',
    name: 'Navin Verma',
    location: 'IIT Bombay',
    avatar: 'https://placehold.co/100x100.png',
    text: 'The Sundarbans honey has a very unique flavour I use it in my morning tea every day It feels so natural and rejuvenating Highly recommend',
    rating: 4,
  },
]
